### ISSUE TITLE
webpack和vite的区别是什么

### ISSUE THREAD

**Issue by xwebing** [xwebing/workDemo#2]
在小程序中，如果一个页面（Page）要传递参数到另一个页面（通常是另一个页面上的自定义组件，Component），可以通过properties来实现。以下是一个简单的例子：

首先，在目标页面的Component定义中添加properties来接收参数：
```javascript
// Component.js
Component({
  properties: {
    // 定义参数，参数类型为String
    paramA: {
      type: String,
      value: ''
    }
  },
  // 组件的方法和生命周期函数
  methods: {
    // 示例方法
    doSomething: function() {
      console.log('参数paramA的值是：' + this.data.paramA);
    }
  }
})
```
在这个例子中，我们定义了一个名为paramA的properties，在页面Page中通过onLoad生命周期函数接收上一页面传递的参数，并通过this.setData将其传递给Component。在Component的.wxml文件中，通过param-a属性将参数传递给Component。
```javascript
// page.js
Page({
onLoad: function(options) {
// 假设我们要传递的参数名为paramA
this.setData({
'paramA': options.paramA
});
}
// 其他页面逻辑
})
```
```css
/* 存在 title 属性的 <a> 元素 */
a[title] {
  color: purple;
}

/* 存在 href 属性并且属性值匹配"https://example.org"的 <a> 元素 */
a[href="https://example.org"]
{
  color: green;
}

/* 存在 href 属性并且属性值包含"example"的 <a> 元素 */
a[href*="example"] {
  font-size: 2em;
}

/* 存在 href 属性并且属性值结尾是".org"的 <a> 元素 */
a[href$=".org"] {
  font-style: italic;
}

/* 存在 class 属性并且属性值包含单词"logo"的<a>元素 */
a[class~="logo"] {
  padding: 2px;
}
```
> ### Version
> 5.3.2
> 
> ### Link to Minimal Reproduction
> https://codepen.io/zz925625/pen/abggQae
> 
> ### Steps to Reproduce
> 鼠标滚动时，右侧y轴位置会变化
> 
> ### Current Behavior
> 如何处理这个
> 
> ### Expected Behavior
> why
> 
> ### Environment
> ```
> - OS:win11
> - Browser:gg125
> - Framework:Vue@3
> ```
> 
> ### Any additional comments?
> _No response_
